type: object
properties:
    type:
        type: string
    name:
        type: string
    task:
        enum:
            - discovery.static
            - discovery.temporal
            - discovery.spatiotemporal
            - classification
    dataset:
        type: object
        properties:
            id:
                type: integer
            files:
                type: object
                patternProperties:
                    ^.*$:
                        type: object
                        properties:
                            index:
                                type: object
                                propertyNames:
                                    enum:
                                        - time
                                        - location
                                        - cause
                                        - effect
                                        - strength
                                        - lag
                                patternProperties:
                                    ^.*$:
                                        type: string
        required:
            - id
    model:
        type: object
        properties:
            id:
                type: integer
            parameters:
                type: object
                propertyNames:
                    enum:
                        - data
                        - space
                patternProperties:
                    ^.*$:
                        type: string
        required:
            - id
            - parameters
    metrics:
        type: array
        items:
            type: object
            properties:
                id:
                    type: integer
                parameters:
                    type: object
                    propertyNames:
                        enum:
                            - ground_truth
                    patternProperties:
                        ^.*$:
                            type: string
            required:
                - id
                - parameters
required:
    - type
    - name
    - task
    - dataset
    - model
    - metrics
