name: CI/CD Test


# Controls when the workflow will run
on:
  push:
    branches:
      - main
  # Triggers the workflow on push or pull request events but only for the develop branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install any other dependencies
        pip install torch

    - name: Build the library
      run: |
        pip install .

    - name: Run Python file
      run: |
        cd tests
        python execute.py  # Replace with the path to your Python file